"""empty message

Revision ID: 09879ea036f3
Revises: 4d1c733a344b
Create Date: 2020-10-08 00:54:41.683410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09879ea036f3'
down_revision = '4d1c733a344b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suscripcion', 'usuario_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('tienda', 'usuario_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tienda', 'usuario_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('suscripcion', 'usuario_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
